services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: api
    environment:
      #--env LITESTREAM_ACCESS_KEY_ID \
      #  --env LITESTREAM_SECRET_ACCESS_KEY \
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
