MAKEFLAGS += --silent

OPTIONS ?= --build --remove-orphans --force-recreate

APP ?= api

all:
	docker-compose up $(OPTIONS) -d

%:
	docker-compose up $(OPTIONS) $@ -d
	docker-compose ps -a

healthcheck:
	docker inspect $(APP) --format "{{ (index (.State.Health.Log) 0).Output }}"

test:
	./tests/e2e.sh

clean:
	docker-compose down --remove-orphans -v --rmi local

-include .env
