name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout 5m

      - name: Build
        run: |
          go get -d -v
          go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./...
