name: github pages
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6.0.0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Build swag documentation config
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g cmd/server/main.go -o tmp --pd --parseInternal

      - name: Build swagger documentation
        run: |
          mkdir -p docs
          python -m pip install --upgrade pip
          pip install pyyml
          python .github/scripts/genswagger-docs.py tmp/swagger.yaml docs/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire directory
          path: docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
